import { useMemo, useState } from 'react'
import { Check, ChevronRight, Eye, EyeOff, Info, Landmark, QrCode, Search, ShieldCheck, ShoppingCart, Star, UserRound, WalletCards, X } from 'lucide-react'
import Navbar from '../components/Navbar'
import AuthModal from '../components/AuthModal'
import { gameAccountGames, getAccount, getAccounts, getGame, readGameAccountCart, rupiahAccount, saveGameAccountCart } from '../data/gameAccountCatalog'
import '../styles/game-accounts.css'

const SERVICE_FEE = 2000

function GameImage({ game, className = '' }) {
  return <img className={className} src={game.image} alt={game.name} onError={(event) => { event.currentTarget.src = '/assets/search/mobile-legends.webp' }} />
}

export function GameAccountsPage() {
  const [query, setQuery] = useState('')
  const visibleGames = useMemo(() => gameAccountGames.filter((game) => `${game.name} ${game.publisher}`.toLowerCase().includes(query.toLowerCase())), [query])
  return <div className="ga-shell"><Navbar variant="loginCatalog"/><main className="ga-picker ga-container">
    <p className="ga-breadcrumb"><a href="/">Beranda</a> / Akun Game</p>
    <h1>Akun Game</h1><p className="ga-lead">Pilih game dulu untuk melihat akun yang tersedia.</p>
    <div className="ga-search-row"><label><Search size={18}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari game atau kategori"/></label><button type="button">Cari</button></div>
    <h2>Game populer</h2>
    <div className="ga-game-grid">{visibleGames.map((game)=><button type="button" className="ga-game-card" key={game.slug} onClick={()=>{window.location.href=`/game-accounts/${game.slug}`}}><GameImage game={game}/><span><strong>{game.name}</strong><small>{game.publisher}</small></span><ChevronRight size={20}/></button>)}</div>
  </main></div>
}

export function GameAccountListingPage({ gameSlug }) {
  const game = getGame(gameSlug)
  const [query, setQuery] = useState('')
  const [tab, setTab] = useState('available')
  const accounts = useMemo(() => getAccounts(game.slug).filter((item) => `${item.title} ${item.region} ${item.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [game.slug, query])
  return <div className="ga-shell"><Navbar variant="loginCatalog"/><main className="ga-list-page ga-container">
    <p className="ga-breadcrumb"><a href="/">Beranda</a> / <a href="/game-accounts">Akun Game</a> / {game.name}</p>
    <header className="ga-list-head"><GameImage game={game}/><div><h1>Akun {game.name}</h1><p>Bandingkan akun berdasarkan rank, hero, item, dan region.</p></div><div className="ga-stock-tabs"><button className={tab==='available'?'active':''} onClick={()=>setTab('available')}>Tersedia (18)</button><button className={tab==='sold'?'active':''} onClick={()=>setTab('sold')}>Sudah Terjual (42)</button></div></header>
    <div className="ga-list-tools"><label><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari rank, hero, item, atau ID listing..."/></label><button>Harga</button><button>Region</button><button>Rank</button><button>Server</button><button>Heroes</button><select defaultValue="recommended"><option value="recommended">Urutkan: Rekomendasi</option><option>Harga Terendah</option></select></div>
    <div className="ga-account-grid">{accounts.filter((item)=>tab==='available'?item.available:!item.available).map((item)=><article className={`ga-account-card${item.available?'':' sold'}`} key={item.slug}><div className="ga-account-art"><GameImage game={game}/>{!item.available&&<span>TERJUAL</span>}</div><div className="ga-account-copy"><h2>{item.title}</h2><p>{item.region} · Level {item.level} · Full access</p><div className="ga-tags">{item.tags.map((tag)=><span key={tag}>{tag}</span>)}</div><strong>{rupiahAccount(item.price)}</strong><button disabled={!item.available} onClick={()=>{window.location.href=`/game-accounts/${game.slug}/${item.slug}`}}>{item.available?'Lihat Detail':'Terjual'}</button></div></article>)}</div>
    <div className="ga-history"><div><strong>Sudah terjual</strong><span>42 akun tersimpan sebagai referensi harga dan spesifikasi.</span></div><button type="button" onClick={()=>setTab('sold')}>Lihat riwayat</button></div>
  </main></div>
}

function RatingStars() { return <span className="ga-stars">{[0,1,2,3,4].map((i)=><Star key={i} size={18} fill="currentColor"/>)}</span> }

export function GameAccountDetailPage({ gameSlug, accountSlug }) {
  const account = getAccount(gameSlug, accountSlug)
  const game = account.game
  const total = account.price + SERVICE_FEE
  function addToCart(){ saveGameAccountCart(account); window.location.href='/cart?flow=account' }
  return <div className="ga-shell"><Navbar variant="loginCatalog"/><main className="ga-detail-page">
    <section className="ga-detail-hero"><GameImage game={game} className="ga-detail-hero-bg"/><div className="ga-detail-scrim"/><div className="ga-container ga-detail-hero-content"><div className="ga-hero-thumb"><GameImage game={game}/></div><div><h1>Akun {game.name} — {account.rank}</h1><div className="ga-hero-rating"><span>Zetruv Digital</span><b>4,8</b><RatingStars/><small>(394)</small></div><div className="ga-hero-badges"><span>⚡ Proses Cepat</span><span>💬 Dukungan Chat 24/7</span><span>◎ Region {account.region}</span></div></div></div></section>
    <div className="ga-container ga-detail-layout"><section className="ga-detail-card"><h2>Detail Akun</h2><div className="ga-detail-specs"><div><small>Rank</small><strong>{account.rank}</strong></div><div><small>Region</small><strong>{account.region}</strong></div><div><small>Account Level</small><strong>{account.level}</strong></div><div><small>Heroes</small><strong>{account.heroes}</strong></div><div><small>Email</small><strong>{account.email}</strong></div></div><div className="ga-review-head"><div><h2>Ulasan Toko</h2><strong>4.8/5</strong><span>394 reviews</span></div><div className="ga-review-bars">{[92,74,42,18,8].map((width,i)=><div key={i}><span>{5-i}</span><i><b style={{width:`${width}%`}}/></i></div>)}</div></div><div className="ga-reviews">{[['D***h','Proses cepat','Produk sesuai'],['A***n','Akun langsung masuk','Respon cepat'],['R***a','Transaksi mudah','Direkomendasikan']].map((review)=><article key={review[0]}><strong>{review[0]}</strong><RatingStars/><p>Transaksi aman dan produk sesuai deskripsi.</p><div><span>{review[1]}</span><span>{review[2]}</span></div></article>)}</div></section>
      <aside className="ga-purchase-card"><h2>Ringkasan Produk</h2><div className="ga-seller"><span>Produk</span><strong>Dijual oleh Zetruv</strong></div><div className="ga-seller"><span>Garansi</span><strong>{account.warranty}</strong></div><div className="ga-warranty"><ShieldCheck size={17}/><span>Garansi transaksi Zetruv aktif sampai akses akun diterima</span></div><div className="ga-selected-account"><strong>Akun {game.name} · {account.rank}</strong><span>{rupiahAccount(account.price)} / akun</span><small>1 akun unik</small></div><div className="ga-summary-row"><span>Subtotal</span><b>{rupiahAccount(account.price)}</b></div><div className="ga-summary-row"><span>Biaya layanan</span><b>{rupiahAccount(SERVICE_FEE)}</b></div><div className="ga-summary-row"><span>Diskon</span><b>Rp0</b></div><hr/><div className="ga-summary-total"><span>Total</span><strong>{rupiahAccount(total)}</strong></div><button className="ga-outline-cta" type="button" onClick={addToCart}>Tambah ke Keranjang</button></aside>
    </div>
  </main></div>
}

export function GameAccountCartPage() {
  const [selected, setSelected] = useState(true)
  const account = readGameAccountCart(); const game=account.game || getGame('dota-2'); const total=account.price+SERVICE_FEE
  return <div className="ga-shell"><Navbar variant="loginCatalog"/><main className="ga-cart ga-container"><header><h1>Keranjang Digital</h1><p>Review akun yang dipilih sebelum lanjut checkout.</p></header><div className="ga-cart-layout"><section className="ga-cart-items"><div className="ga-cart-top"><div><button className={`ga-check${selected?' active':''}`} onClick={()=>setSelected(v=>!v)}>{selected&&<Check size={14}/>}</button><strong>{selected?'1':'0'} akun dipilih</strong></div><button onClick={()=>setSelected(false)}>Hapus pilihan</button></div>{selected&&<article className="ga-cart-item"><button className="ga-check active"><Check size={13}/></button><div className="ga-cart-thumb"><GameImage game={game}/></div><div><h2>Akun {game.name} · {account.rank} · {account.heroes} {game.slug==='mobile-legends'?'Skin':'Heroes'}</h2><span className="ga-destination"><UserRound size={13}/>Region {account.region} · Level {account.level} · Email dapat diubah</span></div><strong>{rupiahAccount(account.price)}</strong><button className="ga-remove" onClick={()=>setSelected(false)}><X size={14}/></button></article>}<div className="ga-info"><Info size={18}/><span>Akun unik ini akan dikunci saat pesanan dibuat. Quantity selalu 1 akun.</span></div></section><aside className="ga-cart-summary"><h2>Ringkasan</h2>{selected&&<div className="ga-summary-item"><span>Akun {game.name} · {account.rank}</span><b>{rupiahAccount(account.price)}</b></div>}<hr/><div className="ga-summary-row"><span>Subtotal</span><b>{rupiahAccount(selected?account.price:0)}</b></div><div className="ga-summary-row"><span>Biaya layanan</span><b>{rupiahAccount(selected?SERVICE_FEE:0)}</b></div><hr/><div className="ga-summary-total"><span>Total</span><strong>{rupiahAccount(selected?total:0)}</strong></div><button className="ga-primary-cta" disabled={!selected} onClick={()=>{window.location.href='/checkout?flow=account'}}>Lanjut ke Checkout <ChevronRight size={15}/></button><small>Merchandise diproses melalui checkout terpisah.</small></aside></div></main></div>
}

function AccountLoginGate({ account, onLoggedIn }) {
  const [showPassword,setShowPassword]=useState(false); const [showRegister,setShowRegister]=useState(false); const game=account.game||getGame('dota-2'); const total=account.price+SERVICE_FEE
  function login(e){e.preventDefault();window.sessionStorage.setItem('zetruv-auth-preview','1');onLoggedIn()}
  return <><header className="ga-gate-title"><h1>Masuk untuk melanjutkan checkout</h1><p>Akun Zetruv diperlukan untuk melanjutkan pembayaran dan melihat status pesanan.</p></header><div className="ga-gate-layout"><section className="ga-gate-card"><h2>Pesanan yang akan dilanjutkan</h2><div className="ga-gate-order"><div><ShoppingCart size={26}/></div><span><strong>1 akun game · {account.rank} · {account.heroes} {game.slug==='mobile-legends'?'Skin':'Heroes'}</strong><small>Keranjang tetap tersimpan</small></span><b>{rupiahAccount(account.price)}</b></div><div className="ga-info"><Info size={18}/><span>Keranjang dan data tujuan akun tetap tersimpan setelah login.</span></div><div className="ga-summary-row"><span>Subtotal</span><b>{rupiahAccount(account.price)}</b></div><div className="ga-summary-row"><span>Biaya layanan</span><b>{rupiahAccount(SERVICE_FEE)}</b></div><hr/><div className="ga-summary-total"><span>Total</span><strong>{rupiahAccount(total)}</strong></div></section><section className="ga-login-card"><h2>Masuk ke akun Zetruv</h2><p>Setelah login, kamu akan kembali ke Checkout Digital untuk memilih metode pembayaran dan menyelesaikan pesanan.</p><form onSubmit={login}><label>Email / username<input required placeholder="nama@email.com" autoComplete="username"/></label><label>Password<div className="ga-password"><input required type={showPassword?'text':'password'} placeholder="••••••••"/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button className="ga-primary-cta" type="submit">Masuk</button><button className="ga-outline-cta" type="button" onClick={()=>setShowRegister(true)}>Buat akun baru</button></form><small>Belum punya akun? Buat akun baru lalu kembali ke checkout.</small></section></div>{showRegister&&<AuthModal mode="register" onClose={()=>setShowRegister(false)} onModeChange={(mode)=>{if(mode==='login')setShowRegister(false)}} onAuthenticated={()=>{window.sessionStorage.setItem('zetruv-auth-preview','1');setShowRegister(false);onLoggedIn()}}/>}</>
}

export function GameAccountCheckoutPage() {
  const account=readGameAccountCart(); const game=account.game||getGame('dota-2'); const [authenticated,setAuthenticated]=useState(()=>window.sessionStorage.getItem('zetruv-auth-preview')==='1'); const [phone,setPhone]=useState('+62 812 3456 7890'); const [voucher,setVoucher]=useState(''); const [method,setMethod]=useState('QRIS'); const total=account.price+SERVICE_FEE
  function pay(){ const invoice=`ACC${Date.now()}INV`; window.sessionStorage.setItem('zetruv-order-preview-v1',JSON.stringify({invoice,items:[account],subtotal:account.price,serviceFee:SERVICE_FEE,total,paymentMethod:method,phone,createdAt:Date.now()}));window.location.href='/payment' }
  return <div className="ga-shell"><Navbar variant="loginCatalog"/><main className="ga-checkout ga-container">{!authenticated?<AccountLoginGate account={account} onLoggedIn={()=>setAuthenticated(true)}/>:<><header><h1>Checkout Digital</h1><p>Periksa kembali detail pesanan, promo, metode pembayaran, dan total.</p></header><div className="ga-checkout-layout"><section className="ga-checkout-order"><h2>Ringkasan Pesanan</h2><div className="ga-checkout-row"><span><strong>Akun {game.name} · {account.rank} · {account.heroes} {game.slug==='mobile-legends'?'Skin':'Heroes'}</strong><small>{game.name} · Region {account.region}</small></span><b>{rupiahAccount(account.price)}</b></div><div className="ga-checkout-row"><span><strong>Detail Akun</strong><small>Level {account.level} · {account.heroes} {game.slug==='mobile-legends'?'Skin':'Heroes'} · Email dapat diubah</small></span><b>Garansi {account.warranty}</b></div><div className="ga-contact"><h3>Informasi Kontak</h3><label>Nomor WhatsApp*<input value={phone} onChange={(e)=>setPhone(e.target.value)}/></label><small>Digunakan jika ada kendala atau update terkait pesanan.</small></div><label className="ga-voucher-label">Kode Voucher</label><div className="ga-voucher"><input value={voucher} onChange={(e)=>setVoucher(e.target.value)} placeholder="Masukkan kode voucher"/><button type="button">Gunakan</button></div><p className="ga-helper">Voucher dapat memberikan potongan sesuai syarat yang berlaku.</p><p className="ga-unique-note">Akun ini unik. Sistem mengecek ulang ketersediaan sebelum order dibuat.</p></section><aside className="ga-payment"><h2>Metode Pembayaran</h2><div className="ga-payment-options">{[['QRIS','Scan QR untuk bayar',QrCode],['Virtual Account','Transfer via bank',Landmark],['E-Wallet','Buka aplikasi wallet',WalletCards]].map(([name,desc,Icon])=><button key={name} type="button" className={method===name?'active':''} onClick={()=>setMethod(name)}><Icon size={28}/><span><strong>{name}</strong><small>{desc}</small></span><i/></button>)}</div><div className="ga-summary-row"><span>Subtotal</span><b>{rupiahAccount(account.price)}</b></div><div className="ga-summary-row"><span>Biaya layanan</span><b>{rupiahAccount(SERVICE_FEE)}</b></div><hr/><div className="ga-summary-total"><span>Total</span><strong>{rupiahAccount(total)}</strong></div><button className="ga-primary-cta" onClick={pay}>Bayar Sekarang</button></aside></div></>}</main></div>
}
